"""empty message

Revision ID: ffb212ddbebc
Revises: d7811402fbd0
Create Date: 2023-06-10 19:40:26.970120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffb212ddbebc'
down_revision = 'd7811402fbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=120),
               type_=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
